"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Pose2D(_message.Message):
    """二维平面位姿。"""

    DESCRIPTOR: _descriptor.Descriptor

    X_M_FIELD_NUMBER: _builtins.int
    Y_M_FIELD_NUMBER: _builtins.int
    YAW_RAD_FIELD_NUMBER: _builtins.int
    x_m: _builtins.float
    """世界坐标系下的 x 坐标，单位米。"""
    y_m: _builtins.float
    """世界坐标系下的 y 坐标，单位米。"""
    yaw_rad: _builtins.float
    """世界坐标系下的偏航角，单位弧度。"""
    def __init__(
        self,
        *,
        x_m: _builtins.float = ...,
        y_m: _builtins.float = ...,
        yaw_rad: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["x_m", b"x_m", "y_m", b"y_m", "yaw_rad", b"yaw_rad"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Pose2D: _TypeAlias = Pose2D  # noqa: Y015
