"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from artemis_mudri.protos.simulation.v1 import common_pb2 as _common_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _EventSeverity:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _EventSeverityEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_EventSeverity.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    EVENT_SEVERITY_UNSPECIFIED: _EventSeverity.ValueType  # 0
    EVENT_SEVERITY_INFO: _EventSeverity.ValueType  # 1
    EVENT_SEVERITY_WARNING: _EventSeverity.ValueType  # 2
    EVENT_SEVERITY_FAILURE: _EventSeverity.ValueType  # 3

class EventSeverity(_EventSeverity, metaclass=_EventSeverityEnumTypeWrapper):
    """半结构化事件的严重程度。"""

EVENT_SEVERITY_UNSPECIFIED: EventSeverity.ValueType  # 0
EVENT_SEVERITY_INFO: EventSeverity.ValueType  # 1
EVENT_SEVERITY_WARNING: EventSeverity.ValueType  # 2
EVENT_SEVERITY_FAILURE: EventSeverity.ValueType  # 3
Global___EventSeverity: _TypeAlias = EventSeverity  # noqa: Y015

@_typing.final
class SimulationEvent(_message.Message):
    """仿真过程中记录的半结构化事件。

    事件采用“稳定外壳 + 半结构化 payload”设计：服务端保证基础字段稳定，具体事件
    含义由 namespace/type/name 与 metrics/labels 共同表达，避免在 proto 中提前定死
    所有训练实验可能需要的事件类型。
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetricsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.float
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.float = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class LabelsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.str
        def __init__(
            self,
            *,
            key: _builtins.str = ...,
            value: _builtins.str = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    TIMESTAMP_S_FIELD_NUMBER: _builtins.int
    PATH_INDEX_FIELD_NUMBER: _builtins.int
    EVENT_ID_FIELD_NUMBER: _builtins.int
    STEP_ID_FIELD_NUMBER: _builtins.int
    NAMESPACE_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    POSE_FIELD_NUMBER: _builtins.int
    METRICS_FIELD_NUMBER: _builtins.int
    LABELS_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """事件名称；保留为主标识，兼容原有路径 checkpoint 事件。"""
    timestamp_s: _builtins.float
    """事件发生时的仿真时间，单位秒。"""
    path_index: _builtins.int
    """事件对应的路径采样点或路径段索引。"""
    event_id: _builtins.int
    """episode 内事件序号，按产生顺序递增。"""
    step_id: _builtins.int
    """事件对应的 step 序号。"""
    namespace: _builtins.str
    """事件命名空间，例如 path、sensor、safety、vehicle、episode。"""
    type: _builtins.str
    """事件类型，例如 checkpoint、state_changed、threshold_crossed、terminated。"""
    severity: Global___EventSeverity.ValueType
    """事件严重程度，便于客户端过滤或统计。"""
    @_builtins.property
    def pose(self) -> _common_pb2.Pose2D:
        """事件发生时的车体位姿。"""

    @_builtins.property
    def metrics(self) -> _containers.ScalarMap[_builtins.str, _builtins.float]:
        """数值型事件 payload，例如 cross_track_error_m、progress_m、duration_s。"""

    @_builtins.property
    def labels(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
        """字符串型事件 payload，例如 segment、source、reason。"""

    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        timestamp_s: _builtins.float = ...,
        path_index: _builtins.int = ...,
        event_id: _builtins.int = ...,
        step_id: _builtins.int = ...,
        namespace: _builtins.str = ...,
        type: _builtins.str = ...,
        severity: Global___EventSeverity.ValueType = ...,
        pose: _common_pb2.Pose2D | None = ...,
        metrics: _abc.Mapping[_builtins.str, _builtins.float] | None = ...,
        labels: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["pose", b"pose"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event_id", b"event_id", "labels", b"labels", "metrics", b"metrics", "name", b"name", "namespace", b"namespace", "path_index", b"path_index", "pose", b"pose", "severity", b"severity", "step_id", b"step_id", "timestamp_s", b"timestamp_s", "type", b"type"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SimulationEvent: _TypeAlias = SimulationEvent  # noqa: Y015
