# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: artemis_mudri/protos/simulation/v1/event.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'artemis_mudri/protos/simulation/v1/event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from artemis_mudri.protos.simulation.v1 import common_pb2 as artemis__mudri_dot_protos_dot_simulation_dot_v1_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.artemis_mudri/protos/simulation/v1/event.proto\x12\x1b\x61rtemis_mudri.simulation.v1\x1a/artemis_mudri/protos/simulation/v1/common.proto\"\xf2\x03\n\x0fSimulationEvent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0btimestamp_s\x18\x02 \x01(\x01\x12\x12\n\npath_index\x18\x03 \x01(\r\x12\x10\n\x08\x65vent_id\x18\x04 \x01(\x04\x12\x0f\n\x07step_id\x18\x05 \x01(\x04\x12\x11\n\tnamespace\x18\x06 \x01(\t\x12\x0c\n\x04type\x18\x07 \x01(\t\x12<\n\x08severity\x18\x08 \x01(\x0e\x32*.artemis_mudri.simulation.v1.EventSeverity\x12\x31\n\x04pose\x18\t \x01(\x0b\x32#.artemis_mudri.simulation.v1.Pose2D\x12J\n\x07metrics\x18\n \x03(\x0b\x32\x39.artemis_mudri.simulation.v1.SimulationEvent.MetricsEntry\x12H\n\x06labels\x18\x0b \x03(\x0b\x32\x38.artemis_mudri.simulation.v1.SimulationEvent.LabelsEntry\x1a.\n\x0cMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\x80\x01\n\rEventSeverity\x12\x1e\n\x1a\x45VENT_SEVERITY_UNSPECIFIED\x10\x00\x12\x17\n\x13\x45VENT_SEVERITY_INFO\x10\x01\x12\x1a\n\x16\x45VENT_SEVERITY_WARNING\x10\x02\x12\x1a\n\x16\x45VENT_SEVERITY_FAILURE\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'artemis_mudri.protos.simulation.v1.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SIMULATIONEVENT_METRICSENTRY']._loaded_options = None
  _globals['_SIMULATIONEVENT_METRICSENTRY']._serialized_options = b'8\001'
  _globals['_SIMULATIONEVENT_LABELSENTRY']._loaded_options = None
  _globals['_SIMULATIONEVENT_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_EVENTSEVERITY']._serialized_start=630
  _globals['_EVENTSEVERITY']._serialized_end=758
  _globals['_SIMULATIONEVENT']._serialized_start=129
  _globals['_SIMULATIONEVENT']._serialized_end=627
  _globals['_SIMULATIONEVENT_METRICSENTRY']._serialized_start=534
  _globals['_SIMULATIONEVENT_METRICSENTRY']._serialized_end=580
  _globals['_SIMULATIONEVENT_LABELSENTRY']._serialized_start=582
  _globals['_SIMULATIONEVENT_LABELSENTRY']._serialized_end=627
# @@protoc_insertion_point(module_scope)
