"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from artemis_mudri.protos.simulation.v1 import common_pb2 as _common_pb2
from artemis_mudri.protos.simulation.v1 import event_pb2 as _event_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ObservationFrame(_message.Message):
    """单帧仿真观测数据。"""

    DESCRIPTOR: _descriptor.Descriptor

    SEQUENCE_ID_FIELD_NUMBER: _builtins.int
    SIM_TIME_S_FIELD_NUMBER: _builtins.int
    LINE_SENSOR_DARKNESS_FIELD_NUMBER: _builtins.int
    IMU_FIELD_NUMBER: _builtins.int
    PATH_PROGRESS_FIELD_NUMBER: _builtins.int
    KINEMATICS_FIELD_NUMBER: _builtins.int
    ORACLE_FIELD_NUMBER: _builtins.int
    STEP_TRACE_FIELD_NUMBER: _builtins.int
    POSE_FIELD_NUMBER: _builtins.int
    sequence_id: _builtins.int
    """服务端观测序号，随仿真步进递增。"""
    sim_time_s: _builtins.float
    """当前仿真时间，单位秒。"""
    @_builtins.property
    def line_sensor_darkness(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]:
        """巡线传感器黑度观测，顺序按传感器阵列从左到右排列。"""

    @_builtins.property
    def imu(self) -> Global___ImuFrame:
        """IMU 航向观测。"""

    @_builtins.property
    def path_progress(self) -> Global___PathProgressFrame:
        """当前路径完成进度。"""

    @_builtins.property
    def kinematics(self) -> Global___KinematicsFrame:
        """车体运动学观测。"""

    @_builtins.property
    def oracle(self) -> Global___OracleFrame:
        """奖励函数可用的真值信息，不应作为策略观测直接输入。"""

    @_builtins.property
    def step_trace(self) -> Global___StepTrace:
        """当前 step 的训练事实记录。服务端只提供事实与事件，不在此处计算 reward。"""

    @_builtins.property
    def pose(self) -> _common_pb2.Pose2D:
        """车体真值位姿，供调试和可视化使用；不应作为训练策略观测直接输入。"""

    def __init__(
        self,
        *,
        sequence_id: _builtins.int = ...,
        sim_time_s: _builtins.float = ...,
        line_sensor_darkness: _abc.Iterable[_builtins.float] | None = ...,
        imu: Global___ImuFrame | None = ...,
        path_progress: Global___PathProgressFrame | None = ...,
        kinematics: Global___KinematicsFrame | None = ...,
        oracle: Global___OracleFrame | None = ...,
        step_trace: Global___StepTrace | None = ...,
        pose: _common_pb2.Pose2D | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["imu", b"imu", "kinematics", b"kinematics", "oracle", b"oracle", "path_progress", b"path_progress", "pose", b"pose", "step_trace", b"step_trace"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["imu", b"imu", "kinematics", b"kinematics", "line_sensor_darkness", b"line_sensor_darkness", "oracle", b"oracle", "path_progress", b"path_progress", "pose", b"pose", "sequence_id", b"sequence_id", "sim_time_s", b"sim_time_s", "step_trace", b"step_trace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ObservationFrame: _TypeAlias = ObservationFrame  # noqa: Y015

@_typing.final
class ImuFrame(_message.Message):
    """IMU 航向观测。"""

    DESCRIPTOR: _descriptor.Descriptor

    YAW_DEG_FIELD_NUMBER: _builtins.int
    YAW_RATE_DEG_S_FIELD_NUMBER: _builtins.int
    yaw_deg: _builtins.float
    """车体偏航角，单位度，范围 [0, 360)。"""
    yaw_rate_deg_s: _builtins.float
    """车体偏航角速度，单位度/秒。"""
    def __init__(
        self,
        *,
        yaw_deg: _builtins.float = ...,
        yaw_rate_deg_s: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["yaw_deg", b"yaw_deg", "yaw_rate_deg_s", b"yaw_rate_deg_s"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ImuFrame: _TypeAlias = ImuFrame  # noqa: Y015

@_typing.final
class KinematicsFrame(_message.Message):
    """车体运动学观测，使用标准物理单位。"""

    DESCRIPTOR: _descriptor.Descriptor

    LONGITUDINAL_VELOCITY_M_S_FIELD_NUMBER: _builtins.int
    LATERAL_VELOCITY_M_S_FIELD_NUMBER: _builtins.int
    YAW_RATE_RAD_S_FIELD_NUMBER: _builtins.int
    longitudinal_velocity_m_s: _builtins.float
    """车体前进方向速度，单位 m/s。"""
    lateral_velocity_m_s: _builtins.float
    """车体侧向速度，单位 m/s。"""
    yaw_rate_rad_s: _builtins.float
    """车体偏航角速度，单位 rad/s。"""
    def __init__(
        self,
        *,
        longitudinal_velocity_m_s: _builtins.float = ...,
        lateral_velocity_m_s: _builtins.float = ...,
        yaw_rate_rad_s: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["lateral_velocity_m_s", b"lateral_velocity_m_s", "longitudinal_velocity_m_s", b"longitudinal_velocity_m_s", "yaw_rate_rad_s", b"yaw_rate_rad_s"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___KinematicsFrame: _TypeAlias = KinematicsFrame  # noqa: Y015

@_typing.final
class OracleFrame(_message.Message):
    """奖励函数可用的真值信息。"""

    DESCRIPTOR: _descriptor.Descriptor

    CROSS_TRACK_ERROR_M_FIELD_NUMBER: _builtins.int
    HEADING_ERROR_RAD_FIELD_NUMBER: _builtins.int
    PROGRESS_INDEX_FIELD_NUMBER: _builtins.int
    PROGRESS_M_FIELD_NUMBER: _builtins.int
    REMAINING_DISTANCE_M_FIELD_NUMBER: _builtins.int
    cross_track_error_m: _builtins.float
    """车体到参考路径最近点的有符号横向误差，单位米。正值表示在路径前进方向左侧，负值表示右侧。"""
    heading_error_rad: _builtins.float
    """车体方向与参考路径切线方向的夹角误差，单位弧度，范围 [-pi, pi]。"""
    progress_index: _builtins.int
    """当前最近路径采样点索引。"""
    progress_m: _builtins.float
    """已沿参考路径推进的距离，单位米。"""
    remaining_distance_m: _builtins.float
    """距离参考路径终点的剩余距离，单位米。"""
    def __init__(
        self,
        *,
        cross_track_error_m: _builtins.float = ...,
        heading_error_rad: _builtins.float = ...,
        progress_index: _builtins.int = ...,
        progress_m: _builtins.float = ...,
        remaining_distance_m: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["cross_track_error_m", b"cross_track_error_m", "heading_error_rad", b"heading_error_rad", "progress_index", b"progress_index", "progress_m", b"progress_m", "remaining_distance_m", b"remaining_distance_m"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___OracleFrame: _TypeAlias = OracleFrame  # noqa: Y015

@_typing.final
class PathProgressFrame(_message.Message):
    """路径与事件完成进度。"""

    DESCRIPTOR: _descriptor.Descriptor

    ACTIVE_SEGMENT_INDEX_FIELD_NUMBER: _builtins.int
    COMPLETED_EVENT_COUNT_FIELD_NUMBER: _builtins.int
    COMPLETED_EVENTS_FIELD_NUMBER: _builtins.int
    REACHED_GOAL_FIELD_NUMBER: _builtins.int
    PROGRESS_INDEX_FIELD_NUMBER: _builtins.int
    PROGRESS_M_FIELD_NUMBER: _builtins.int
    DELTA_PROGRESS_M_FIELD_NUMBER: _builtins.int
    REMAINING_DISTANCE_M_FIELD_NUMBER: _builtins.int
    active_segment_index: _builtins.int
    """当前所在路径段索引。"""
    completed_event_count: _builtins.int
    """已完成事件数量。"""
    reached_goal: _builtins.bool
    """是否已到达路径终点。"""
    progress_index: _builtins.int
    """当前最近路径采样点索引。"""
    progress_m: _builtins.float
    """已沿参考路径推进的距离，单位米。"""
    delta_progress_m: _builtins.float
    """相比上一帧推进的路径距离，单位米；可用于客户端 reward shaping。"""
    remaining_distance_m: _builtins.float
    """距离参考路径终点的剩余距离，单位米。"""
    @_builtins.property
    def completed_events(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """已完成事件名称列表。"""

    def __init__(
        self,
        *,
        active_segment_index: _builtins.int = ...,
        completed_event_count: _builtins.int = ...,
        completed_events: _abc.Iterable[_builtins.str] | None = ...,
        reached_goal: _builtins.bool = ...,
        progress_index: _builtins.int = ...,
        progress_m: _builtins.float = ...,
        delta_progress_m: _builtins.float = ...,
        remaining_distance_m: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_segment_index", b"active_segment_index", "completed_event_count", b"completed_event_count", "completed_events", b"completed_events", "delta_progress_m", b"delta_progress_m", "progress_index", b"progress_index", "progress_m", b"progress_m", "reached_goal", b"reached_goal", "remaining_distance_m", b"remaining_distance_m"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PathProgressFrame: _TypeAlias = PathProgressFrame  # noqa: Y015

@_typing.final
class TrainingTraceConfig(_message.Message):
    """训练侧事件与真值遥测输出配置。

    该配置只决定服务端返回哪些可复现事实，不定义 reward。reward 应由训练客户端
    基于 ObservationFrame、OracleFrame、StepTrace 和 SimulationEvent 自行计算。
    """

    DESCRIPTOR: _descriptor.Descriptor

    INCLUDE_ORACLE_FIELD_NUMBER: _builtins.int
    INCLUDE_STEP_EVENTS_FIELD_NUMBER: _builtins.int
    INCLUDE_EPISODE_EVENTS_FIELD_NUMBER: _builtins.int
    REWARD_PROFILE_FIELD_NUMBER: _builtins.int
    include_oracle: _builtins.bool
    """是否在每帧返回 oracle 真值遥测。"""
    include_step_events: _builtins.bool
    """是否在每帧返回本 step 新触发的事件。"""
    include_episode_events: _builtins.bool
    """是否在 episode 结束汇总中返回完整事件日志。"""
    reward_profile: _builtins.str
    """客户端用于标记 reward/训练实验配置的名称，服务端仅透传到日志或诊断信息。"""
    def __init__(
        self,
        *,
        include_oracle: _builtins.bool = ...,
        include_step_events: _builtins.bool = ...,
        include_episode_events: _builtins.bool = ...,
        reward_profile: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["include_episode_events", b"include_episode_events", "include_oracle", b"include_oracle", "include_step_events", b"include_step_events", "reward_profile", b"reward_profile"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TrainingTraceConfig: _TypeAlias = TrainingTraceConfig  # noqa: Y015

@_typing.final
class StepTrace(_message.Message):
    """单个环境 step 的事实记录。

    该结构对应 Gymnasium step 返回值中的 done/info 事实部分，但不包含 reward。
    """

    DESCRIPTOR: _descriptor.Descriptor

    STEP_ID_FIELD_NUMBER: _builtins.int
    ACTION_SEQUENCE_ID_FIELD_NUMBER: _builtins.int
    DT_S_FIELD_NUMBER: _builtins.int
    TERMINATED_FIELD_NUMBER: _builtins.int
    TRUNCATED_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    EVENTS_FIELD_NUMBER: _builtins.int
    step_id: _builtins.int
    """服务端 step 序号，随仿真推进递增。"""
    action_sequence_id: _builtins.int
    """触发本 step 的客户端动作序号；初始观测没有对应动作时为 0。"""
    dt_s: _builtins.float
    """本 step 的仿真时长，单位秒。"""
    terminated: _builtins.bool
    """当前 episode 是否因为任务成功或失败自然终止。"""
    truncated: _builtins.bool
    """当前 episode 是否因为时间上限、客户端停止或外部原因被截断。"""
    reason: _builtins.str
    """终止或截断原因；未结束时为空。"""
    @_builtins.property
    def events(self) -> _containers.RepeatedCompositeFieldContainer[_event_pb2.SimulationEvent]:
        """本 step 新触发的半结构化事件。"""

    def __init__(
        self,
        *,
        step_id: _builtins.int = ...,
        action_sequence_id: _builtins.int = ...,
        dt_s: _builtins.float = ...,
        terminated: _builtins.bool = ...,
        truncated: _builtins.bool = ...,
        reason: _builtins.str = ...,
        events: _abc.Iterable[_event_pb2.SimulationEvent] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["action_sequence_id", b"action_sequence_id", "dt_s", b"dt_s", "events", b"events", "reason", b"reason", "step_id", b"step_id", "terminated", b"terminated", "truncated", b"truncated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StepTrace: _TypeAlias = StepTrace  # noqa: Y015
