"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from artemis_mudri.protos.simulation.v1 import common_pb2 as _common_pb2
from artemis_mudri.protos.simulation.v1 import event_pb2 as _event_pb2
from artemis_mudri.protos.simulation.v1 import observation_pb2 as _observation_pb2
from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ClientMessage(_message.Message):
    """客户端发往仿真服务的流式消息。"""

    DESCRIPTOR: _descriptor.Descriptor

    START_FIELD_NUMBER: _builtins.int
    CONTROL_COMMAND_FIELD_NUMBER: _builtins.int
    STOP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def start(self) -> Global___StartEpisodeRequest:
        """启动 episode 的请求，必须作为流中的第一条消息发送。"""

    @_builtins.property
    def control_command(self) -> Global___VehicleControlCommand:
        """环境动作：后双驱目标速度命令，用于推进一段控制周期。"""

    @_builtins.property
    def stop(self) -> Global___StopEpisodeRequest:
        """主动停止当前 episode 的请求。"""

    def __init__(
        self,
        *,
        start: Global___StartEpisodeRequest | None = ...,
        control_command: Global___VehicleControlCommand | None = ...,
        stop: Global___StopEpisodeRequest | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["control_command", b"control_command", "payload", b"payload", "start", b"start", "stop", b"stop"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["control_command", b"control_command", "payload", b"payload", "start", b"start", "stop", b"stop"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["start", "control_command", "stop"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___ClientMessage: _TypeAlias = ClientMessage  # noqa: Y015

@_typing.final
class StartEpisodeRequest(_message.Message):
    """启动一次仿真 episode 的参数。"""

    DESCRIPTOR: _descriptor.Descriptor

    MAX_TIME_S_FIELD_NUMBER: _builtins.int
    CONTROL_PERIOD_S_FIELD_NUMBER: _builtins.int
    INITIAL_POSE_FIELD_NUMBER: _builtins.int
    INITIAL_PROGRESS_INDEX_FIELD_NUMBER: _builtins.int
    RANDOM_SEED_FIELD_NUMBER: _builtins.int
    TRAINING_TRACE_FIELD_NUMBER: _builtins.int
    max_time_s: _builtins.float
    """本次 episode 的最大仿真时长，单位秒；0 表示使用服务端默认时间上限。"""
    control_period_s: _builtins.float
    """控制周期，单位秒；0 表示使用仿真后端默认步长。"""
    initial_progress_index: _builtins.int
    """手动指定 oracle 路径进度搜索的初始采样点索引；不设置时从路线起点开始。"""
    random_seed: _builtins.int
    """可选随机种子；不设置或为 0 时由服务端采用默认随机策略。"""
    @_builtins.property
    def initial_pose(self) -> _common_pb2.Pose2D:
        """手动指定车辆初始位姿；不设置时使用路线默认起点。"""

    @_builtins.property
    def training_trace(self) -> _observation_pb2.TrainingTraceConfig:
        """训练侧所需的事件与真值遥测输出配置；不设置时服务端使用默认输出策略。"""

    def __init__(
        self,
        *,
        max_time_s: _builtins.float = ...,
        control_period_s: _builtins.float = ...,
        initial_pose: _common_pb2.Pose2D | None = ...,
        initial_progress_index: _builtins.int = ...,
        random_seed: _builtins.int = ...,
        training_trace: _observation_pb2.TrainingTraceConfig | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["initial_pose", b"initial_pose", "training_trace", b"training_trace"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["control_period_s", b"control_period_s", "initial_pose", b"initial_pose", "initial_progress_index", b"initial_progress_index", "max_time_s", b"max_time_s", "random_seed", b"random_seed", "training_trace", b"training_trace"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StartEpisodeRequest: _TypeAlias = StartEpisodeRequest  # noqa: Y015

@_typing.final
class VehicleControlCommand(_message.Message):
    """车辆控制命令。"""

    DESCRIPTOR: _descriptor.Descriptor

    SEQUENCE_ID_FIELD_NUMBER: _builtins.int
    REAR_LEFT_TARGET_SPEED_FIELD_NUMBER: _builtins.int
    REAR_RIGHT_TARGET_SPEED_FIELD_NUMBER: _builtins.int
    sequence_id: _builtins.int
    """客户端侧命令序号，用于排查丢包、乱序或日志对齐。"""
    rear_left_target_speed: _builtins.float
    """后左电机目标速度，单位为编码器脉冲/20ms。"""
    rear_right_target_speed: _builtins.float
    """后右电机目标速度，单位为编码器脉冲/20ms。"""
    def __init__(
        self,
        *,
        sequence_id: _builtins.int = ...,
        rear_left_target_speed: _builtins.float = ...,
        rear_right_target_speed: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["rear_left_target_speed", b"rear_left_target_speed", "rear_right_target_speed", b"rear_right_target_speed", "sequence_id", b"sequence_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VehicleControlCommand: _TypeAlias = VehicleControlCommand  # noqa: Y015

@_typing.final
class StopEpisodeRequest(_message.Message):
    """客户端主动停止 episode 的请求。"""

    DESCRIPTOR: _descriptor.Descriptor

    REASON_FIELD_NUMBER: _builtins.int
    reason: _builtins.str
    """停止原因；为空时服务端使用默认原因。"""
    def __init__(
        self,
        *,
        reason: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reason", b"reason"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StopEpisodeRequest: _TypeAlias = StopEpisodeRequest  # noqa: Y015

@_typing.final
class ServerMessage(_message.Message):
    """服务端发回客户端的流式消息。"""

    DESCRIPTOR: _descriptor.Descriptor

    STARTED_FIELD_NUMBER: _builtins.int
    OBSERVATION_FIELD_NUMBER: _builtins.int
    FINISHED_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    error: _builtins.str
    """episode 执行失败或请求不合法。"""
    @_builtins.property
    def started(self) -> Global___EpisodeStarted:
        """episode 已启动并返回运行参数。"""

    @_builtins.property
    def observation(self) -> _observation_pb2.ObservationFrame:
        """仿真观测帧。"""

    @_builtins.property
    def finished(self) -> Global___EpisodeFinished:
        """episode 已结束并返回汇总结果。"""

    def __init__(
        self,
        *,
        started: Global___EpisodeStarted | None = ...,
        observation: _observation_pb2.ObservationFrame | None = ...,
        finished: Global___EpisodeFinished | None = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "finished", b"finished", "observation", b"observation", "payload", b"payload", "started", b"started"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "finished", b"finished", "observation", b"observation", "payload", b"payload", "started", b"started"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_payload: _TypeAlias = _typing.Literal["started", "observation", "finished", "error"]  # noqa: Y015
    _WhichOneofArgType_payload: _TypeAlias = _typing.Literal["payload", b"payload"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_payload) -> _WhichOneofReturnType_payload | None: ...

Global___ServerMessage: _TypeAlias = ServerMessage  # noqa: Y015

@_typing.final
class EpisodeStarted(_message.Message):
    """episode 启动后的运行参数。"""

    DESCRIPTOR: _descriptor.Descriptor

    TIME_LIMIT_S_FIELD_NUMBER: _builtins.int
    CONTROL_PERIOD_S_FIELD_NUMBER: _builtins.int
    time_limit_s: _builtins.float
    """服务端默认时间上限，单位秒。"""
    control_period_s: _builtins.float
    """本次 episode 实际采用的控制周期，单位秒。"""
    def __init__(
        self,
        *,
        time_limit_s: _builtins.float = ...,
        control_period_s: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["control_period_s", b"control_period_s", "time_limit_s", b"time_limit_s"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EpisodeStarted: _TypeAlias = EpisodeStarted  # noqa: Y015

@_typing.final
class EpisodeFinished(_message.Message):
    """episode 结束消息。"""

    DESCRIPTOR: _descriptor.Descriptor

    SUMMARY_FIELD_NUMBER: _builtins.int
    REASON_FIELD_NUMBER: _builtins.int
    FINAL_STEP_TRACE_FIELD_NUMBER: _builtins.int
    reason: _builtins.str
    """结束原因，例如 goal_reached、time_limit、client_stopped 或 viewer_closed。"""
    @_builtins.property
    def summary(self) -> Global___SimulationSummary:
        """本次 episode 的汇总统计。"""

    @_builtins.property
    def final_step_trace(self) -> _observation_pb2.StepTrace:
        """结束时对应的 step 事实记录，便于训练客户端对齐终止/截断语义。"""

    def __init__(
        self,
        *,
        summary: Global___SimulationSummary | None = ...,
        reason: _builtins.str = ...,
        final_step_trace: _observation_pb2.StepTrace | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["final_step_trace", b"final_step_trace", "summary", b"summary"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["final_step_trace", b"final_step_trace", "reason", b"reason", "summary", b"summary"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___EpisodeFinished: _TypeAlias = EpisodeFinished  # noqa: Y015

@_typing.final
class SimulationSummary(_message.Message):
    """episode 汇总统计。"""

    DESCRIPTOR: _descriptor.Descriptor

    REACHED_GOAL_FIELD_NUMBER: _builtins.int
    ELAPSED_TIME_S_FIELD_NUMBER: _builtins.int
    ROUTE_LENGTH_M_FIELD_NUMBER: _builtins.int
    MAX_CROSS_TRACK_ERROR_M_FIELD_NUMBER: _builtins.int
    RMS_CROSS_TRACK_ERROR_M_FIELD_NUMBER: _builtins.int
    FINAL_POSE_FIELD_NUMBER: _builtins.int
    EVENTS_FIELD_NUMBER: _builtins.int
    TOTAL_STEPS_FIELD_NUMBER: _builtins.int
    reached_goal: _builtins.bool
    """是否到达路径终点。"""
    elapsed_time_s: _builtins.float
    """实际经过的仿真时间，单位秒。"""
    route_length_m: _builtins.float
    """路径总长度，单位米。"""
    max_cross_track_error_m: _builtins.float
    """最大横向路径误差，单位米。"""
    rms_cross_track_error_m: _builtins.float
    """横向路径误差均方根，单位米。"""
    total_steps: _builtins.int
    """episode 总 step 数。"""
    @_builtins.property
    def final_pose(self) -> _common_pb2.Pose2D:
        """episode 结束时的车体位姿。"""

    @_builtins.property
    def events(self) -> _containers.RepeatedCompositeFieldContainer[_event_pb2.SimulationEvent]:
        """episode 中记录到的路径事件。"""

    def __init__(
        self,
        *,
        reached_goal: _builtins.bool = ...,
        elapsed_time_s: _builtins.float = ...,
        route_length_m: _builtins.float = ...,
        max_cross_track_error_m: _builtins.float = ...,
        rms_cross_track_error_m: _builtins.float = ...,
        final_pose: _common_pb2.Pose2D | None = ...,
        events: _abc.Iterable[_event_pb2.SimulationEvent] | None = ...,
        total_steps: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["final_pose", b"final_pose"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["elapsed_time_s", b"elapsed_time_s", "events", b"events", "final_pose", b"final_pose", "max_cross_track_error_m", b"max_cross_track_error_m", "reached_goal", b"reached_goal", "rms_cross_track_error_m", b"rms_cross_track_error_m", "route_length_m", b"route_length_m", "total_steps", b"total_steps"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SimulationSummary: _TypeAlias = SimulationSummary  # noqa: Y015
